---
- name: Converge
  hosts: 
    - ubuntu2004
    - debian10
    - rockey8
  tasks:
    - name: Install crontab
      ansible.builtin.apt:
        name: cron
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install crontab
      ansible.builtin.yum:
        name: crontabs
        state: latest
      when: ansible_os_family == "RedHat"

    - name: "Include iquzart.crontab_prometheus_exporter"
      ansible.builtin.include_role:
        name: "iquzart.crontab_prometheus_exporter"
      vars:
        cron_script_dir: /opt/cron-job-scripts
        cron_job_name: example_job
        cron_job: uname -a