name: Molecule Test
on:
  push:
    paths-ignore: 
      - README.md
      - .travis.yml
    branches: [ main ]
  label:
    types: [created, edited]
  pull_request:
    branches:    
      - main
      - 'releases/**'
#   schedule:
#     - cron: '30 5 * * 1,3'      
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: diquzart/molecule:latest
      options: --privileged
    steps:
      - name: clone repo
        run: |
          git clone "https://github.com/${{ github.repository }}.git" .
        
      - name: test podman
        run: |
          podman ps

      - name: Test with molecule
        run: |
          molecule test
